version: "3"
services:
  proxy-nginx:
    image: nginx:1.23.4
    container_name: proxy-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf.template
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - SOME_CUSTOM_HEADER=dummy
      - ENDPOINT=http://contents-nginx:8090
    command: >
      /bin/bash -c "envsubst '$$SOME_CUSTOM_HEADER $$ENDPOINT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
      && nginx -g 'daemon off;'"
  contents-nginx:
    # 動的モジュールを追加したいため、個別ビルド
    build:
      context: ./contents
      dockerfile: Dockerfile
    container_name: contents-nginx
    ports:
      - "8090:8090"
    volumes:
      - ./contents/default.conf:/etc/nginx/conf.d/default.conf
      - ./contents/nginx.conf:/etc/nginx/nginx.conf
      - ./contents/index.html:/usr/share/nginx/html/index.html
  k6:
    image: grafana/k6:0.41.0
    container_name: k6
    volumes:
      - type: bind
        source: ./k6/src
        target: /src
    environment:
      - TIME_UNIT=100ms
      - DURATION=10s
      - TARGET_PATH=/
    # entrypoint: ["sh", "-c", "k6 run /src/script.js"]
    entrypoint: ["sleep", "1h"]
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
